### ISSUE TITLE
'fstp tbyte ptr' -> should be 'fstp tword ptr' ?!

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#108]
`0x0069A807 - DB BD C0 FD FF FF`

x32dbg:
![image](https://user-images.githubusercontent.com/14368203/87251617-70febf00-c45c-11ea-9b0a-0eb38464c07e.png)
Capstone:
![image](https://user-images.githubusercontent.com/14368203/87251697-1b76e200-c45d-11ea-837d-345d6ab3b22b.png)
iced:
![image](https://user-images.githubusercontent.com/14368203/87251644-b3280080-c45c-11ea-8ad5-1fe75587c385.png)

Which one is correct?

**Comment by 0xd4d** [comment]
`tbyte ptr` is what masm uses and that's why you see iced's masm formatter use it. The `t` in `tbyte` means `ten` and that's the size of the memory location.

**Comment by Symbai** [comment]
so `tword` and `tbyte` are identical? Or does x32dbg uses something different than masm and that's what it makes it a `tword` instead of a `tbyte` ?

**Comment by 0xd4d** [comment]
`tword` is what nasm uses but it doesn't use `ptr` so it seems to be a mix of masm and nasm.
