### ISSUE TITLE
Possibility to set the current offset in CodeReader?

### ISSUE THREAD

**Issue by Washi1337** [0xd4d/iced#110]
**Summary:**
The `Decoder` / `CodeReader` classes only really support a linear sweep disassembly of the input stream as far as I can tell. This is fine if the input data is well structured. However, for non-linear disassembly procedures like a recursive traversal which I am implementing in one of my projects, this does not work, since we often need to move around the file more in a more sporadic way than just from top to bottom.

Is there any intention to add support for setting the current offset of a `CodeReader` object, or should we use in such a case one of the derived classes of `CodeReader` (e.g. `ByteArrayCodeReader`)?

**Example:**
Simplest example I could think of that shows this behaviour:
```csharp
var code = new byte[]
{
   /* 0: */ 0xEB, 0x01,  // jmp    0x3
   /* 2: */ 0xFF,        // db     0xFF
   /* 3: */ 0xC3         // ret
};
```

Note that the `ret` might also appear before the `jmp` in the input stream.

**Workarounds:**
Current workaround for me is to use the derived classes `ByteArrayCodeReader`, which does define a `Position` property. Alternatively I could also use the `StreamCodeReader` and modify the `Position` property of the underlying `Stream` object.

Simplified example code (this should of course check if the decoded instruction is a branch, but for brevity I kept it out):

```csharp
var reader = new ByteArrayCodeReader(code);
var decoder = Decoder.Create(32, reader);

// Decode the jmp
decoder.Decode(out var instruction);
Console.WriteLine(instruction);

// Follow branch target.
reader.Position = (int) instruction.NearBranchTarget;
decoder.IP = instruction.NearBranchTarget;

// Continue disassembly.
decoder.Decode(out instruction);
Console.WriteLine(instruction);
```

**Comment by 0xd4d** [comment]
The CodeReader has a very simple API, just a `ReadByte` method because that's the only thing the decoder needs.. I have no plans to add any other methods or properties to this class. If you need to change the offset, you should do what you do above and use your own CodeReader class or ByteArrayCodeReader which allows setting a new position.

**Comment by Washi1337** [comment]
Makes perfect sense. Thanks.
