### ISSUE TITLE
Add Instruction.HasOpKind(Opkind kind)

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#114]
Often Iced says something like `"Use this property if the operand has kind Opkind.xxxx"`. There is currently no one liner to check that. The instruction may have up to 5 opkinds. Therefore it would be really useful to have a function for that, so we can do this instead of iterating through all kinds ourselves:

```
if (instruction.HasOpKind(Opkind.Memory))
{
    memoryBase = instruction.MemoryBase;
}
```

I could make a PR for that if the suggestion gets approved.

**Comment by 0xd4d** [comment]
This won't work if it's a register since you don't know which Op{XXX}Register property it is. It only works if it's some OpKind that can appear at most once in all operands.

Why don't you iterate over all operands in a loop?

**Comment by Symbai** [comment]
>  
> Why don't you iterate over all operands in a loop?

That is why I am doing currently, but as extension method because I have to do this multiple times at different locations in my code. However it seems to be useful and natural enough to add this officially into Iced:

```
namespace Iced.Intel.IntelFormatterInternal {

  public readonly bool HasOpKind(InstrOpKind opkind) {
   //loop here
  }

}
```

**Comment by 0xd4d** [comment]
Sure, send a PR!
