### ISSUE TITLE
Rename IsStackInstruction to IsModifyingStack and add a new IsUsingStack

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#116]
The current `IsStackInstruction` is a bit false leading as by its name I would assume it tells me whether the instruction uses the stack. In fact it only tells whether it modifies the stack. For example it returns `FALSE` for `mov rbx,[rsp+40]`.

So I would suggest to rename the property and also add a new one which tells us if the instruction reads the stack (or is there a quick iteration-free way to do right now?)

**Comment by 0xd4d** [comment]
It returns true if it uses the stack implicitly, either by reading from the stack or writing to it (i.e., pushing or popping). The docs mention this too.

**Comment by Symbai** [comment]
I know that the docs say that but the name is still misleading, because it ONLY returns true if the stack is modified. Popping or pushing the stack, changes the stack. It either removes or adds a value to it. In both cases the stack is modified. So `IsModifyingStack` describe what it does.

mov rbx,[rsp+40]

READS from the stack. It reads the value at `rsp+40` and moves it into `RBX`. `IsStackInstruction` returns false. But it does something ( = reading) with the stack.

**Comment by 0xd4d** [comment]
Popping only reads from the stack, so nothing on the stack is changed.

`MOV` is not a stack instruction. Any instruction that references memory could be reading from or writing to the area allocated to the stack, eg. `mov eax,[rbx]` could be reading from the stack.

A stack instruction (in iced at least) is any instruction that implicitly pushes or pops the stack, eg. `CALL`, `PUSH`, `RET`, etc.

**Comment by Symbai** [comment]
> Popping only reads from the stack, so nothing on the stack is changed.

On the stack is nothing changed but the stack itself is changed as the stack pointer changes:
![image](https://user-images.githubusercontent.com/14368203/90330038-5064e000-df99-11ea-8000-4b85d94f5aff.png)


> eg. `mov eax,[rbx]` could be reading from the stack.

That however is true and a good argument. Convinced me to say that what I am looking for is not the right thing.
