### ISSUE TITLE
Enhancement: `UsedMemory.virtual_address()`?

### ISSUE THREAD

**Issue by woodruffw** [0xd4d/iced#124]
First of all, thanks a _ton_ for this library -- it's easily one of the most polished and user-friendly x86/AMD64 decoders I've used (and I've used quite a few).

Currently (in Rust), the `Instruction` struct has a `virtual_address` (and `try_virtual_address`) member function that takes an operand index and, if it's a memory operand, uses a callback to concretize the operand's addressing form into a specific virtual address. This is _incredibly_ handy when working at the `Instruction` level.

When working slightly below the `Instruction` level at the `InstructionInfo`/`UsedMemory` level, there's no such helper function. As such, I propose that `UsedMemory.virtual_address()` (and `try_virtual_address`) as an enhancement to that part of the API.

Here's a proposed API (just `virtual_address`, for brevity):

```rust
impl UsedMemory {
  pub fn virtual_address<F>(&self, get_register_state: F) -> u64
  where
      F: FnMut(Register) -> u64 {
      // ...
  }
}
```

...where `get_register_state` would be expected to concretize the base and index registers, provided that they're not `Register::None`. I could also throw in the VSIB parameters, where appropriate.

Let me know if this sounds interesting to you. It's something I'm happy to work on (and capable of contributing).

**Comment by 0xd4d** [comment]
Yes this is useful, if you want to send a PR, please do!

**Comment by woodruffw** [comment]
> Yes this is useful, if you want to send a PR, please do!

Will do! I'll look at implementing this in the coming week :slightly_smiling_face:
