### ISSUE TITLE
Signed numbers with custom symbol resolver

### ISSUE THREAD

**Issue by Nprimus** [0xd4d/iced#13]
Hi,

I'm using a custom symbol resolver to overwrite the display symbol. The displacement is given as ulong in all bitness. The problem starts with 32bit and possibly also 16bit and detecting unsigned negative numbers. The symbol resolver does not give any information about the current bitness being used.

With the following code I filter out negative numbers which works fine in 64bit. In 32bit it passes the filter obviously and later on the displacement is handled as symbol and the formatter doesn't show the value as signed when set in options. 

I think it would be nice to also pass the bitness as parameter so I can cast the displacement to int when I can be completey sure its safe to cast and then check it again. What do you think?

```
 public override bool TryGetDisplSymbol(int operand, Code code, ulong displacement, ref bool ripRelativeAddresses, out SymbolResult symbol, ref NumberFormattingOptions options)
        {
            symbol = default;
            if ((long)displacement < 0x0) return false;
			//not negative, do action here.
             symbol = new SymbolResult(displacement.ToString("X")); //gives someting like 0xFFFF in 32bit

}
```

**Comment by 0xd4d** [comment]
If you only overwrite the symbol result with a hex number, you should update 'options' instead since you can force hex, signed, etc. Note that the caller assumes branch offsets are always unsigned.

Passing in some more info such as size of immediate could be useful though.

**Comment by Nprimus** [comment]
Hi,

this was just an example. Its not always the case I return a hex number string though it happens. Options is already set to show signed numbers. Also tried setting the flag in symbolresult struct to signed but in all cases it displays what I return in symbol resolver. Which will be unsigned negative hex string when displacement is unsigned negative number (in example above only in 32bit). Thats however not the actual problem. 

The problem is that I don't know how to check the displacement is negative without knowing the bitness.

**Comment by 0xd4d** [comment]
The SymbolResolver methods now get the size of the immediate/address. The instruction is also passed in by ref and the Code value arg is removed.
