### ISSUE TITLE
Assembler - Specify the variable types to generate different bytecode

### ISSUE THREAD

**Issue by Nekketsu** [0xd4d/iced#133]
There are many instructions in the assembler that can generate different assembly code and bytecode depending on the variable values or types.
For example:
- `asm.push(0x10)` generates: `push imm8 0x10` -> `0x6A 0x10`
- `asm.push(0x10101010)` generates: `push imm16/imm32 0x10101010` -> `0x68 0x10 0x10 0x10 0x10`

I'd like to control the assembly instructions and bytecode generated.

I have the situation where I have a C method like:
`void Calculate(int value);`
And I'd like to generate assembly code able to call the method. The problem is that depending on the value I push, it generates a compatible or incompatible code.

Does it exist any way to have such kind of control?

Some solutions could be:
1. Add an optional parameter to specify the type, something like: `asm.push(10, AssemblerParameterType.Imm32)`.
2. Automatically generate different assembly code depending on the C# type: `byte`, `short`, `ushort`, `int`, `uint`, etc.
3. Have a different method name for each possible type: `asm.push_imm32(10)`.

Maybe, my favorite option is options number 1, because we can have control over the parameter type if we specify a second parameter. But we could also not specify the second parameter and let the assembler to generate the most optimal assembly code.

**Comment by Symbai** [comment]
```
asm.mov(ecx, 0x10)
asm.push(ecx)
```

**Comment by Nekketsu** [comment]
Thank you. But the problem I see is that I generate a bigger bytecode, and I don't have control about what instructions and how the bytecode will be generated.

**Comment by Symbai** [comment]
If you're using registers you have full control. 

Small byte code:
```
asm.mov(cx, 0x10)
asm.push(cx)
```
Normal byte code
```
asm.mov(ecx, 0x10)
asm.push(ecx)
```
Large byte code:
```
asm.mov(rcx, 0x10)
asm.push(rcx)
```

**Comment by Nekketsu** [comment]
Normal byte code:
```
B910000000      MOV ECX, 0x10
51              PUSH ECX
```

Immediate byte code:
`6810000000      PUSH 0x10`

Isn't it possible to generate the  "Immediate byte code"? Why do I have to generate a larger bytecode as a workaround.
Compare "Normal byte code" vs "Immediate byte code". And it doesn't take into account have to back up the original value of "ECX" if necessary.

Don't we have control to generate the "Immediate byte code"? The only work around I saw was to manually generate the bytecode:
```
asm.db(0x68);
asm.db(BitConverter.GetBytes(0x10));
```

If I use:
`asm.push(0x10);`

It pushes a BYTE and not a DWORD, as I need:
`6A10            PUSH 0x10`

I'd like to have total control about the generated assembly instructions and bytecode.

Is not possible to generate following assembly instruction without using a workaround?:
`6810000000      PUSH 0x10`

**Comment by Symbai** [comment]
This is the default behavior on all assemblers. If you assemble "push 0x10" it always generates the lowest sized instruction. It only creates a dword instruction if the integer you pushes requires it.  In order to push a dword based on a small number, you need to use a 32bit register. Or you need to store it and use a "push dword ptr [ xxxx ]" instruction. Or you choose your way and write the assembled bytes directly in case you know the bytes.

But to be fair when you suggest an optional overload I don't see a problem with it. So I'm not against your suggestions I only wanted to point out alternative solutions.

**Comment by Nekketsu** [comment]
If I am not wrong, the assemblers have directives to specify the size of the operand. For example, I think this is a valid NASM syntax to push the 32bit value 0x10:
`PUSH DWORD 0X10`

I don't know what is the best solution. Maybe, in the same way we can specify the memory size with `__dword_ptr`, it could be something like `__dword` to specify the immediate value:
`asm.push(__dword(0x10));`

**Comment by Symbai** [comment]
That's a very good idea, I like that one.

**Comment by 0xd4d** [comment]
Both `o32 68 id` and `o32 6A ib` push 32 bits of data which is exactly what your 32-bit func expects. Iced picks the smaller one when it can so it doesn't use more bytes than needed.

In the unlikely event that you must use the longer form even when the shorter form can be used, you can use `db()` and `dd()`. There are no plans to add overrides where you can specify the size of the immediates.

**Comment by Nekketsu** [comment]
Thank you for the clarification. Knowing that both instructions push 32 bits of data, then it's not important to have such level of control.
