### ISSUE TITLE
Instruction data tables

### ISSUE THREAD

**Issue by flobernd** [0xd4d/iced#14]
Hey there,

I'm one of the [Zydis](https://github.com/zyantific/zydis) (a x86-64 disassembler written in C) devs. I noticed you reported some definition bugs in the Intel xed repository.

As we are comparing our disassembly against xed and other disassemblers, we are curious to know if you do a similar thing and what sources you used for your data-tables. Did you compose them by hand using the official documentation?

Best regards

**Comment by 0xd4d** [comment]
Only official Intel and AMD docs so far, but I know that sandpile has some undocumented instructions so will have a look there later.

**Comment by flobernd** [comment]
Cool. Thanks for the answer.
