### ISSUE TITLE
Rationale behind instruction code

### ISSUE THREAD

**Issue by xoofx** [0xd4d/iced#16]
Hey,
So while trying to encode a simple x86 instruction:

```C#
using System;
using System.Collections.Generic;
using Iced.Intel;

namespace TestIced {
	public class Program {


		public static void Main() {
			var codeWriter = new CodeWriterImpl();
			var encoder = Encoder.Create32(codeWriter);
			var inst = new Instruction {
				Code = Code.Mov_EAX_Id,
				OpCount = 2,
				Op0Kind = OpKind.Register,
				Op0Register = Register.EAX,
				Op1Kind = OpKind.Immediate32,
				Immediate32 = 125,
			};
			string errorMessage;
			var nextRip = encoder.Encode(ref inst, 0, out errorMessage);
			var array = codeWriter.ToArray();
			foreach (var b in array) {
				Console.Write($"{b:X2} ");
			}
		}

		sealed class CodeWriterImpl : CodeWriter {
			readonly List<byte> allBytes = new List<byte>();
			public override void WriteByte(byte value) => allBytes.Add(value);
			public byte[] ToArray() => allBytes.ToArray();
		}
	}
}
```

What is confusing is the `Code.Mov_EAX_Id` where I need to replicate the information of the register in Op0Register. So I'm wondering why you couldn't use closer abstract instruction code for it like it is expressed in Intel documentation `MOV r32, imm32`?

**Comment by 0xd4d** [comment]
The decoder will always add those values, it makes it easier to analyze the instructions. But I agree if you're only creating instructions to encode them the encoder already knows which register is supposed to be operand #0 and it knows that opkind must be Register.

I decided to map each Code value to an opcode instead of using eg. one Mov for all kinds of mov instructions. The encoder implementation is trivial and it doesn't have to guess anything, and the programmer has full control of which opcode should be used (eg. should 'add eax,ecx' use opcode 01h or 03h).

I will probably make OpCount read only as well since it's a known value.

**Comment by xoofx** [comment]
But couldn't we have something like `Code.Mov_r32_imm32` instead? So that it is matching what we can find in regular doc and it is easier to match. I'm not proposing to have only `Code.Mov` because as you said, you would have to detect which final `mov` is going to be used,  (That would be an enum of the column `Instruction` in the Intel doc or the column Mnemonic from this [x86 reference](https://c9x.me/x86/html/file_module_x86_id_176.html))

**Comment by xoofx** [comment]
For my usage, I'm just tinkering with the idea to play with a simple compiler written in C# to x86/x64.

**Comment by 0xd4d** [comment]
Yes that's possible and is probably a good idea, there are a couple of those instructions, eg. one-byte 'push/pop reg', 'inc/dec reg'.

**Comment by xoofx** [comment]
Even for push they represent them as `Push_r32` for example 

![image](https://user-images.githubusercontent.com/715038/45553982-9b1dd080-b835-11e8-9745-d94070761953.png)

Even if it is one byte, you can still represent it with an abstract mnemonic and not `Push_Eax`.
It would be easier overall for iced if to follow this notation for opcodes.

**Comment by xoofx** [comment]
I could try to make a prototype of this change just for the mov instruction, if you want?

**Comment by 0xd4d** [comment]
Yes, feel free to do that!

**Comment by xoofx** [comment]
On the matter of simplify instruction creation, what could be the API for it? I have a few questions regarding what can be improved. Let's take the previous example and try to use this API:

```c#
var mov1 = Instruction.Create(Code.Mov_r32_imm32, Register.EAX, 127);
```
Many overrides of `Instruction.Create` would have to be created for the different operands variations, while opcodes would be valid mainly to one overload...

Then `Instruction.Create` would actually fill the proper bits related from Code.Mov_r32_imm32` to the `Instruction` (`OpCount = 2`, `Op0Kind = OpKind.Register`, `Op1Kind = OpKind.Immediate32`). Is it something you have in mind? Should encoding go through an error message or an exception?

**Comment by 0xd4d** [comment]
There are many instructions with the exact same operands, so I don't think it will be too many Create() overloads. Eg. there are a lot of reg,reg and reg,mem or reg,reg,reg and reg,reg,mem instructions and they would all use one of the 4 previous Create() overloads.

`OpCount` should be made readonly since all Code values have a fixed number of operands.

> Should encoding go through an error message or an exception?

I prefer an error message (that's what the Encoder does today), but if needed a new API could be created that throws, maybe `EncodeThrow()`.

**Comment by xoofx** [comment]
> I prefer an error message (that's what the Encoder does today), but if needed a new API could be created that throws, maybe EncodeThrow().

Could we have something reversed where by using `Try` prefix?

```C#
var mov1 = Instruction.TryCreate(Code.Mov_r32_imm32, Register.EAX, 127, out errorMessage);
var mov1 = Instruction.Create(Code.Mov_r32_imm32, Register.EAX, 127, out errorMessage); 
```

**Comment by 0xd4d** [comment]
I misread it, I thought it was the Encoder, but it was Instruction.Create() only.

I don't think it's worth checking for errors in Create(). They could verify that the register is a GPR32 and throw if it's eg an XMM register, but it would require extra code. The encoder will already check this when you try to encode it. If you create a new Instruction, it's highly likely that you'll encode it later.

**Comment by xoofx** [comment]
> I don't think it's worth checking for errors in Create(). They could verify that the register is a GPR32 and throw if it's eg an XMM register, but it would require extra code. The encoder will already check this when you try to encode it. If you create a new Instruction, it's highly likely that you'll encode it later.

Oh that's right. So what about `Encoder.TryEncode(..., out errorMessage)` and `Encoder.Encode(...)` throwing an exception?

**Comment by 0xd4d** [comment]
Yes that would match the .NET Framework API names so would be better than adding a EncodeThrow() method.

**Comment by 0xd4d** [comment]
I've pushed the new Create() methods to master. The encoder does most of the validation.

**Comment by xoofx** [comment]
> I've pushed the new Create() methods to master. The encoder does most of the validation.

Amazing, it looks good 👍

**Comment by xoofx** [comment]
So from what I gather, the remaining list with `+rb/rw/rd/ro` encoding should be this one:

```
Code.Inc_r16
Code.Inc_r32
Code.Dec_r16
Code.Dec_r32
Code.Mov_r8_imm8
Code.Mov_r16_imm16
Code.Mov_r32_imm32
Code.Mov_r64_imm64
Code.Pop_r16
Code.Pop_r32
Code.Pop_r64
Code.Push_r16
Code.Push_r32
Code.Push_r64
Code.Xchg_AX_r16
Code.Xchg_EAX_r32
Code.Xchg_RAX_r64
```

Is that correct?

**Comment by 0xd4d** [comment]
And: Bswap_r16, Bswap_r32, Bswap_r64

**Comment by xoofx** [comment]
> And: Bswap_r16, Bswap_r32, Bswap_r64

Ah yes, good catch

**Comment by 0xd4d** [comment]
Do you want to keep this open or should I close it?

**Comment by xoofx** [comment]
No it's all fine now, thanks for allowing this change!
