### ISSUE TITLE
Icon for Iced?

### ISSUE THREAD

**Issue by xoofx** [0xd4d/iced#23]
Hey, would you be interested in using a dedicated icon for iced (mostly nuget package)?

For my projects, I'm usually using one that I can found on the Noon Project (with proper CC licensing and credits in the readme).

For example from ["this list with processor chip"](https://thenounproject.com/search/?q=processor%20chip) keywords

I can make a PR with this one for example: https://thenounproject.com/search/?q=processor%20chip&i=176265 but if you find one more appealing, it's your project, go ahead! 😉 

I have an account on their website, I can send a PR.

**Comment by 0xd4d** [comment]
Yes, send a PR!
