### ISSUE TITLE
Encode by string

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#27]
Hi,

I've looked at the examples and the test classes but I cannot figure out. Is there a way to encode an instruction by a string? So I pass "mov eax, 4" and get the byte array representation of it?

In case there isn't, is there a workaround or chance to add it?

**Comment by 0xd4d** [comment]
It can encode instructions but not assemble instructions. I have no plan to add an assembler, you can try masm/nasm/as if you want to assemble instructions.
