### ISSUE TITLE
Disable .NET Core tiered compilation

### ISSUE THREAD

**Issue by 0xd4d** [0xd4d/iced#29]
I got worse perf with tiered compilation enabled. It will be enabled by default in .NET Core 3.0.

**Comment by xoofx** [comment]
Is this something that you were able to report to CoreCLR?

**Comment by 0xd4d** [comment]
Enabling AggressiveOptimization didn't do much. Possibly related to:

https://github.com/dotnet/coreclr/issues/20282
https://github.com/dotnet/coreclr/issues/19752
