### ISSUE TITLE
Way to get memorydisplacement index?

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#31]
Is there a way to get the index of the memorydisplacement of the byte representation?

For example:
`F30F1087F8000000 => movss     xmm0,[rdi+0F8h]`

What I'm looking for is to get the position where it starts (5. byte) and ends (8. byte). I'd need it to build wild card byte arrays, where the memory displacement might get replaced by ?? when it meets or does not meet a specific criteria. Currently i'm converting the memory displacement back into bytes and do a lookup but this isn't 100% safe like in example below where 0x40 appears twice in byte array:

`C7404001000000 => mov       dword [rax+40h],1`

**Comment by 0xd4d** [comment]
You can call Decoder.GetConstantOffsets()

**Comment by Symbai** [comment]
Amazing, exactly what I've been looking for. Is there a chance this can be extended to include registers?

**Comment by Symbai** [comment]
Is it possible to obtain the offsets also from an Iced.Instruction? Without using encoder, then codewriter to obtain byte array, then create decoder and finally decoder.getconstantoffsets.

**Comment by 0xd4d** [comment]
No, only the decoder and encoder would know about that info.
