### ISSUE TITLE
GetMaxEncodedByteCount?

### ISSUE THREAD

**Issue by Zhentar** [0xd4d/iced#36]
I used iced as a JIT assembler in https://github.com/Zhentar/CLRStackZeroingAssemblyTests and one of the issues I noticed was that if my current allocation isn't large enough, I can only allocate a new larger buffer and copy it over if the assembly is position independent (because the new location would mean a new RIP). It would be helpful to be able to get a rough, pessimistic size estimate in advance so I can start off with a large enough destination instead of needing to start over encoding.

**Comment by 0xd4d** [comment]
As a workaround, if you know that you don't have any branch instructions that could be rewritten to 2+ instructions, you can just calculate `instruction count * 15 bytes` (15 = max instruction length).

You could also pass in a dummy `CodeWriter` that doesn't write anything, it just increments a counter which you can read later. That should be the exact size you need to allocate.
