### ISSUE TITLE
BlockEncoder - Skip invalid instructions

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#37]
An option to skip / stop at invalid instructions but keep all re-encoded instructions would be nice so we can still use all new encoded instructions (up to the point where iced discovered an invalid instruction) in codewriter.

//edit: Preferably I would like it just copies the invalid bytes until it receives a valid instruction again. Or making it a choice how to proceed when an invalid instruction is detected (abort completely, stop but keep reencoded instructions, copy bytes until a valid instruction is detected).

**Comment by 0xd4d** [comment]
Why would anyone want to ignore invalid instructions?

What is an invalid instruction? An instruction with `Code == INVALID` and/or an instruction that failed to assemble for some reason (eg. unsupported ops such as `xor ax,ecx`)?

If it's `Code == INVALID` you can easily filter out those instructions before trying to encode instructions.

**Comment by 0xd4d** [comment]
If you get non-decodable instructions, you're most likely trying to decode data.

**Comment by Symbai** [comment]
> Why would anyone want to ignore invalid instructions?

Because it breaks re-encoding a memory block just because iced has a problem with some bytes? Like 0x7 I dont care if Iced cannot reassemble it, if it cannot then just copy the byte because there is no need to re-encode it, it won't be different on different memory address but it breaks re-encoding completely.

> If it's `Code == INVALID` you can easily filter out those instructions before trying to encode instructions.

I can but it's getting difficult. Imagine the invalid instruction is in the middle of the memory block. I would have to take care that instructions after this getting re-assembling according the correct memory address. I cannot simply "skip" the instruction without making sure that instructions after it remain at the same memory address.

**Comment by 0xd4d** [comment]
> Because it breaks re-encoding a memory block just because iced has a problem with some bytes? Like 0x7 I dont care if Iced cannot reassemble it, if it cannot then just copy the byte because there is no need to re-encode it, it won't be different on different memory address but it breaks re-encoding completely.

Invalid instructions don't contain the data, so it's not possible for the encoder to encode anything.

As a workaround, replace all invalid instructions with enough nops. Then overwrite the result (the nops) with the original data.

**Comment by Symbai** [comment]
The encoder doesn't have to encode it, just copy the original bytes. It can still internally handle it as "invalid instruction" as long as it doesn't break re-encoding a memory block. As of now, I have to catch tryencode, then iterate through the instruction list finding invalid instructions, then replace the bytes and store every instruction position, then on codewriter.ToArray() iterating through it again, taking care about byte size per instruction, find every single instruction that is "faulty" and insert original bytes.

That is actually very complex and costs much resources when iced could just keep the original bytes without re-encoding the invalid instruction. Let it be invalid, don't reencode, remain original bytes, that's all.

**Comment by 0xd4d** [comment]
You should add some control flow analysis so you don't decode data. If you decode from the beginning to the end you will eventually decode data and get random instructions or INVALID instructions.

```asm
jmp @F
db 0B8h
@@:
call method
```

Even if iced stored the bytes in invalid instructions so you could encode it back, some of that data could be bytes of valid instructions, as seen above.

I plan on adding new Code values so you can easily write arbitrary bytes to the output, see #40. You could replace those INVALID values with a 'db'. The best solution would be for you to do some cflow analysis so you only decode instructions not data.
