### ISSUE TITLE
Invalid instruction - Iced missing "pop es" = 0x7

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#39]
64-Bit, bytes `0x7` is  `pop es` instruction but iced incorrectly reports `invalid (bad)`. Verified using https://onlinedisassembler.com/odaweb/

//edit : On architecture i368 it produces pop es. Setting it explicitly to 32 or 64-bit using the web disassembler however returns bad instruction the same as iced returns, why? I currently have the problem that I cannot re-encode a memory block because it stops at `0x7` while some other disassemblers just resolve it as `pop es`. Perhaps https://github.com/0xd4d/iced/issues/37 can solve this problem?

**Comment by 0xd4d** [comment]
`pop es` is a 16/32-bit instruction only. That link above defaults to i386 (32-bit code). Switch to i386-x64-64 and it will also show `(bad)`.
