### ISSUE TITLE
Null Reference Exception in NumberFormatter

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#41]
I've updated to latest version and experienced a null reference exception in https://github.com/0xd4d/iced/blob/689cbd3934639ceb47edfae4ada391c43563a1b3/Iced/Intel/NumberFormatter.cs#L159

It happens using this code:

```
var output = new StringBuilderFormatterOutput();
var masm = new MasmFormatter();
masm.Format(ref op, output);
```

I believe it was introduced with commit https://github.com/0xd4d/iced/commit/6c2b5f3feb46b30ff1d86fe4629fbb2499c9c1ac#diff-dd18d807ae1dce9a22708afd4cf40506 What was the reason to allow passing null without setting option field to a value?

**Comment by 0xd4d** [comment]
I can't repro it, do you have a complete repro example?

The commit above always initializes the field to a non-null value so it can't be related to this issue.

**Comment by 0xd4d** [comment]
I could repro it, it was a arg vs field issue. The arg was passed to its ctor when it should've been the field.
