### ISSUE TITLE
the example should be updated

### ISSUE THREAD

**Issue by wwh1004** [0xd4d/iced#46]
![Snipaste_2019-09-04_23-41-25](https://user-images.githubusercontent.com/27536652/64270405-0c3a2480-cf6e-11e9-8fc0-4591a8661a31.png)

.net core and .net fx 4.7 are the same

**Comment by 0xd4d** [comment]
It works with current master. If you use the latest nuget, use the example in the older version of the README: https://github.com/0xd4d/iced/blob/7e2bea40e11de3bddbfde15be0f218b0ebba8335/README.md
