### ISSUE TITLE
Add a new higher level instruction encoder

### ISSUE THREAD

**Issue by 0xd4d** [0xd4d/iced#49]
It should be easier to use, eg. methods with same name as mnemonics `add(eax, 123)`. There are a couple libraries already eg. x86: https://github.com/asmjit/asmjit, ARM: https://android.googlesource.com/platform/external/vixl

The current instruction encoder should be used by the new one

**Comment by xoofx** [comment]
Hey,

I have played with a wrapper around Iced in my own project and come up with a syntax like this:

![image](https://user-images.githubusercontent.com/715038/71778982-63034980-2fb4-11ea-8ae6-934ff84aceb7.png)

And with memory operand (notice the usage of the syntax `__[` to open:

![image](https://user-images.githubusercontent.com/715038/71778988-672f6700-2fb4-11ea-8a55-861418eb99ed.png)

Is that in line with what you had in mind? 
Would you be interested If I try to make a PR? Not sure I will have time to implement all methods, likely most of the stuffs could be auto-generated although in my prototype I wrote it manually...

**Comment by 0xd4d** [comment]
Yes these methods should be auto generated, if possible, since I need to implement that in Rust too. :)

A PR is welcome it would be have to be against the rust branch since I've moved files around.

That `__[]` thing is interesting. Is it using C# expressions?

**Comment by xoofx** [comment]
> That __[] thing is interesting. Is it using C# expressions?

No, it is way more simple, using a simple struct, it should be quite in line with how Iced is build (no GC and stack friendly):

```
        public static IntelMemoryOperandFactory __ => new IntelMemoryOperandFactory();
// ....
    public readonly struct IntelMemoryOperandFactory
    {
        public IntelMemoryOperand this[IntelMemoryOperand operand] => operand;

        public IntelMemoryOperand this[IntelRegister operand] => new IntelMemoryOperand(Register.None, operand, Register.None, 1, 0);
    }
``` 

Then `IntelMemoryOperand` and `IntelRegister` are simple struct wrappers around `Register` and `MemoryOperand` but they provide overloads for `*` `+` operators,

**Comment by 0xd4d** [comment]
That's even better, no allocations. :)

**Comment by xoofx** [comment]
In my code, for an instruction like push, I have something like this:

```c#
		public void push(Register reg) {
			Code op;
			if (reg.IsGPR64()) {
				op = Code.Push_r64;
			}
			else if (reg.IsGPR32()) {
				op = Code.Push_r32;
			}
			else if (reg.IsGPR16()) {
				op = Code.Push_r16;
			}
			else {
				throw new ArgumentException($"Invalid register size `{reg}` for `{nameof(push)}` instruction. Expecting 16/32/64.");
			}
			_encoder.Encode(Instruction.Create(op, reg), pc);
		}
```

Is it ok with the approach or would you see something different here for the codegen?

**Comment by 0xd4d** [comment]
The `push reg` code looks complete, it covers all supported regs. And I like that you checked the 64-bit reg first, should be more common. ;)

It would be nice to also support code labels and memory operands that can access the user's data. Does your code support that?

**Comment by xoofx** [comment]
> The push reg code looks complete, it covers all supported regs. And I like that you checked the 64-bit reg first, should be more common. ;)

Cool, thanks, I will try to come up with a first prototype.

> It would be nice to also support code labels and memory operands that can access the user's data. Does your code support that?

For label, I haven't done anything yet... I haven't checked how Iced is working with label actually so far 😅. How is working the current approach in Iced for handling labels with branches when encoding?

> memory operands that can access the user's data

Not sure to see what usage this could be. Do you have an example?

**Comment by 0xd4d** [comment]
> For label, I haven't done anything yet... I haven't checked how Iced is working with label actually so far 😅. How is working the current approach in Iced for handling labels with branches when encoding?

If you create instructions yourself and use the BlockEncoder, you have to initialize the branch instruction's `NearBranch64` property with the "IP" of the target instruction. The "IP" can be anything as long as it's unique. `je.NearBranch64 = unique_id; target_instr.IP = unique_id;`

> Not sure to see what usage this could be. Do you have an example?

If you add code, chances are you need data too. Could be some ASCII string in the code or a lookup table for a switch statement.

It should be easier to use BlockEncoder instead of Encoder since BlockEncoder can also optimize jcc near to jcc short.

**Comment by xoofx** [comment]
> It should be easier to use BlockEncoder instead of Encoder since BlockEncoder can also optimize jcc near to jcc short.

Ok, right, I will try to do that, thanks!

**Comment by xoofx** [comment]
Hey, while working on the API with `BlockEncoder` , I was wondering what is the rationale of having a `CodeWriter` attached to a `IntrumentBlock` (so you could end-up having different `CodeWriter`), instead of passing it just one time at `TryEncode` time as a separate parameter from `IntrumentBlock`/`IntrumentBlock[]`?

**Comment by 0xd4d** [comment]
So it's possible to write to 2 different buffers if you pass in 2 blocks. If you have just one writer, each block must be next to the other in the same buffer.

**Comment by 0xd4d** [comment]
@xoofx's great work has been merged into master. I'll probably release 1.5.0 next week.
