### ISSUE TITLE
Add a masm formatter option to use `st(0)` instead of `st`

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#52]
Settings:
```
var formatter = new MasmFormatter();
formatter.Options.DigitSeparator = "";
```
Input:
`{ 0xD8, 0xC9 }`
produces:
`fmul st,st(1)`
expected:
`fmul st(0),st(1)`

**Comment by 0xd4d** [comment]
The output is valid masm syntax.

An option to use st(0) could be added since masm also accepts st(0).

**Comment by Symbai** [comment]
That's what I was about to say too. Both is valid but I prefer its showing (0) but it currently does not and i couldn't find a setting for it so it would be nice to have one.
