### ISSUE TITLE
Resolving JNE Short rel8 (16-bit Intel)

### ISSUE THREAD

**Issue by enusbaum** [0xd4d/iced#56]
First off - love the library, it has been really outstanding.

I'm running into an issue on how a JNE rel8 is being decided. The below is the code in question:
`0002.093Dh 751D` 

Expected (verified in IDA):
`jne short 095Ch`

Actual:
`jne short 0A0Ch`

I noticed that Iced is identifying the operand size as '16', which I suspect is the issue here.

My implementation of the decoder for the segment data is as follows:
```C#
//Decode the Segment
var instructionList = new InstructionList();
var codeReader = new ByteArrayCodeReader(segment.Data);
var decoder = Decoder.Create(16, codeReader);
decoder.IP = 0x0;

while (decoder.IP < (ulong)segment.Data.Length)
{
	decoder.Decode(out instructionList.AllocUninitializedElement());
}
```

**Comment by 0xd4d** [comment]
I can't repro it with this code. Make sure decoder.IP is initialized correctly.

```C#
var reader = new ByteArrayCodeReader("751D");
var decoder = Decoder.Create(16, reader);
decoder.IP = 0x093D;
decoder.Decode(out var instr);
Console.WriteLine(instr.ToString());
// Output: jne short 095Ch
```

**Comment by enusbaum** [comment]
Thanks for the quick reply! I'm looking through the disassembly now of the segment. 

You're right -- I think the IP starts to drift in the disassembly. Let me track that down and I'll follow up.

**Comment by enusbaum** [comment]
So - I verified the IP and it's correct in both my IP register and within the Iced disassembly (attached screen shot).

```
0002:09DB enter 4,0
0002:09DF push ds
0002:09E0 mov ax,0FFFFh
0002:09E3 mov ds,ax
0002:09E5 cmp byte ptr ds:[8FFh],0
0002:09EA jne short 0A0Ch
```
![image](https://user-images.githubusercontent.com/1139047/70454788-06764280-1a79-11ea-97d5-76b027995a8c.png)

![image](https://user-images.githubusercontent.com/1139047/70454866-39b8d180-1a79-11ea-85f0-79834dc575c4.png)

**Comment by 0xd4d** [comment]
So is `0002:09EA jne short 0A0Ch` wrong? The only way for the target offset to be wrong is if decoder.IP wasn't correct when decoding it. Have you verified that decoder.IP was `0x09EA` when that instruction was decoded? My repro above shows that as long as the IP is correct, you get the correct output.

**Comment by enusbaum** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/626dd453-b50e-4ee9-9dce-86d306043c85-699cd42f-b1a1-4912-9584-0279ae63be9b-v1.png?transparent=1&palette=1&width=246)

You are correct... I was comparing it to the wrong entry point...

Completely my bad on this one.
