### ISSUE TITLE
Skip memory size info on multi nop

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#57]
Bitness: x64
Data: `66 0F 1F 44 00 00`
Formatter: NASM

Options:
`formatter.Options.MemorySizeOptions = MemorySizeOptions.Minimum;`
or:
`formatter.Options.MemorySizeOptions = MemorySizeOptions.Default;`

Output:
` nop       word [rax+rax]`

Expected:
` nop       [rax+rax]`

On multi nop instruction the formatter can likely always skip posting the memory size info, unless MemorySizeOptions is set to always. Unlike on other instructions the memory size is not necessary to know.

Related #9

**Comment by 0xd4d** [comment]
The memory size is required because there are 3 versions, a 16-bit, a 32-bit and a 64-bit version.

**Comment by Symbai** [comment]
Sure but iced only disassembles right? It does not assemble by a string. So the memory size of a nop should be irrelevant unlike the memory size of a MOV instruction because you cannot tell yourself what exactly happens when reading it, while for a nop... its a nop.

**Comment by Symbai** [comment]
Well I think you're right and it's probably better to have it there. Who knows for which purpose people are using Iced.
