### ISSUE TITLE
Unexpected Immediate64 value on instruction without immediate

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#61]
`48 89 4C 24 38  == mov [rsp+38h],rcx`
```
Console.WriteLine($"{tab}HasImmediate: {offsets.HasImmediate || offsets.HasImmediate2}");
Console.WriteLine($"{tab}Immediate16: {instr.Immediate16:X}");
Console.WriteLine($"{tab}Immediate32: {instr.Immediate32:X}");
Console.WriteLine($"{tab}Immediate64: {instr.Immediate64:X}");
```
Iced output:

> HasImmediate: False
> Immediate16: 0
> Immediate32: 0
> Immediate64: **3800000000**
> 

Shouldn't it rather be **00**00000000 instead?

**Comment by 0xd4d** [comment]
No, the operand is only valid if `GetOpKind(i) == OpKind.Immediate64`

**Comment by 0xd4d** [comment]
Maybe you're looking for `GetImmediate(operand)` which you can call if the operand is an immediate.

**Comment by Symbai** [comment]
Why does the immediate property has any value if the instruction has no immediate?

**Comment by 0xd4d** [comment]
If you mean why it's non-zero, it's because I try to keep the `Instruction` struct as small as possible. Some bits are re-used. It's 32 bytes, there are some free bits left. Compare that to other decoders where a decoded instruction can be anywhere from a few 100 bytes to almost 1KB in size.

**Comment by Symbai** [comment]
Yes that's what I meant. Good to know, thanks for explaining
