### ISSUE TITLE
Assembler: Add nop(int count) overload

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#64]
Often we know the number of nops to generate but not which multi nop instruction covers the desired size. It would be great if the assembler gets an overload for the amount of nops to generate and choose the appropriate nop instruction based on this.

Example Scenario:
```
c.nop(8)
c.Encode(); // == 0F 1F 84 00 00 00 00 00 == nop dword ptr [rax+rax]

c.nop(5)
c.Encode(); // == 0F 1F 44 00 00 == nop dword ptr [rax+rax]
```

This would also solve the problem of two basically identical looking instructions like above when we try to assemble them on our own: 

```
c.nop(__dword_ptr [rax + rax]); 
c.Encode(); // == 0F 1F 04 00 == invalid length
```

**Comment by 0xd4d** [comment]
This is from Intel SDM:

Count | Instruction | Bytes
------|-------------|------
1 byte  | NOP | 90H
2 bytes | 66 NOP | 66 90H
3 bytes | NOP DWORD ptr [EAX] |  0F 1F 00H
4 bytes | NOP DWORD ptr [EAX + 00H] | 0F 1F 40 00H
5 bytes | NOP DWORD ptr [EAX + EAX*1 + 00H] | 0F 1F 44 00 00H
6 bytes | 66 NOP DWORD ptr [EAX + EAX*1 + 00H] | 66 0F 1F 44 00 00H
7 bytes | NOP DWORD ptr [EAX + 00000000H] | 0F 1F 80 00 00 00 00H
8 bytes | NOP DWORD ptr [EAX + EAX*1 + 00000000H] | 0F 1F 84 00 00 00 00 00H
9 bytes | 66 NOP DWORD ptr [EAX + EAX*1 + 00000000H] | 66 0F 1F 84 00 00 00 00 00H


It should be easy to implement. The code would just add `db(x,x,...)`. If it's 16-bit mode, some other nop instructions may be needed since the above code assumes 32/64-bit addressing.

**Comment by Symbai** [comment]
I don't really know where/how the `Assembler.g.cs` file is created and which I need to modify in order to add an overload, otherwise I would try to help by submitting a PR. Meanwhile I am using this as workaround which works for nearly unlimited number of nops:

```
static class AssemblerExtensions {
		public static void nop(this Assembler c, int numberOfNops) {
			if (numberOfNops <= 0) return;
			int cycles = Math.DivRem(numberOfNops, 9, out int rest);

			for (int i = 0; i < cycles; i++) {
				AppendNop(ref c, 9);
			}

			AppendNop(ref c, rest);

			static void AppendNop(ref Assembler c, int numberOfNops) {
				Debug.Assert(numberOfNops > 0 && numberOfNops <= 9);
				switch (numberOfNops) {
				case 1:
					c.db(0x90); //NOP
					break;
				case 2:
					c.db(0x66, 0x90); //66 NOP
					break;
				case 3:
					c.db(0x0F, 0x1F, 0x00); //NOP DWORD ptr [EAX]
					break;
				case 4:
					c.db(0x0F, 0x1F, 0x40, 0x00); //NOP DWORD ptr [EAX + 00H]
					break;
				case 5:
					c.db(0x0F, 0x1F, 0x44, 0x00, 0x00); //NOP DWORD ptr [EAX + EAX*1 + 00H]
					break;
				case 6:
					c.db(0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00); //66 NOP DWORD ptr [EAX + EAX*1 + 00H]
					break;
				case 7:
					c.db(0x0F, 0x1F, 0x80, 0x00, 0x00, 0x00, 0x00); //NOP DWORD ptr [EAX + 00000000H]
					break;
				case 8:
					c.db(0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00); //NOP DWORD ptr [EAX + EAX*1 + 00000000H]
					break;
				case 9:
					c.db(0x66, 0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00); //66 NOP DWORD ptr [EAX + EAX*1 + 00000000H] 	
					break;

				}
			}
		}
	}
```

**Comment by xoofx** [comment]
> I don't really know where/how the `Assembler.g.cs` file is created and which I need to modify in order to add an overload, otherwise I would try to help by submitting a PR. Meanwhile I am using this as workaround which works for nearly unlimited number of nops:

No need to modify `Assembler.g.s`, you can add this method directly to `Assembler.cs`, with proper checks and ArgumentOutOfRangeException, handling of bitness support (if any)...etc.

**Comment by 0xd4d** [comment]
These can be used if it's 16-bit mode:

Bytes | 16-bit Instruction
------|-------------------
90 | nop
66 90 | 66 nop
0F 1F 00 | nop word ptr [bx+si]
0F 1F 40 00 | nop word ptr [bx+si]
0F 1F 80 00 00 | nop word ptr [bx+si]
66 0F 1F 80 00 00 | nop dword ptr [bx+si]
67 66 0F 1F 44 00 00 | nop dword ptr [eax+eax]
67 0F 1F 80 00 00 00 00 | nop word ptr [eax]
67 0F 1F 84 00 00 00 00 00 | nop word ptr [eax+eax]

**Comment by Symbai** [comment]
Will send a PR later
