### ISSUE TITLE
Assembler - Add Symbol Resolver

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#70]
Ideally the assembler would accept string parameters everywhere and calling a symbol resolver immediately to get the number it stands for, but I'm not sure if this is doable that easily. But if I am wrong then this allows very neat assembling flow like this which makes assembling in bigger context more readable and requires less code:

#### Usage:
```
var c = new Assembler(64);
c.SymbolResolver += (e,s) => {
	if (s == "Kernel32.ExitProcess")
		return 0x40000;
}

c.sub(rsp,28)
c.mov(rax,1)
c.call("Kernel32.ExitProcess");
c.add(rsp,28)
c.ret();
```

But in case a pure string is not an option, an alternative solution would be that we would need a Symbol struct which behaves similar to the Register and represents a number. The symbol number is unknown until the assembler accesses it, calling the symbol resolver returning the actual value.

#### Propose:
```
public partial class Assembler {
	public AssemblerSymbol CreateSymbol(string key) => return new AssemblerSymbol(key);
}

public struct AssemblerSymbol : IEquatable<AssemblerSymbol> {

	public AssemblerSymbol(string key) { ... } 

	/// <summary>
	/// The unique key identifier
	/// </summary>
	public string Key;
	
	/// <summary>
	/// The actual value
	/// </summary>
	public long Value;

	public static bool operator ==(AssemblerSymbol left, AssemblerSymbol right) => left.Equals(right);

	public static bool operator !=(AssemblerSymbol left, AssemblerSymbol right) => !left.Equals(right);

	public static bool operator +(AssemblerSymbol left, AssemblerSymbol right) => left.Value + right.Value;
	public static bool operator -(AssemblerSymbol left, AssemblerSymbol right) => left.Value - right.Value;
	public static bool operator /(AssemblerSymbol left, AssemblerSymbol right) => left.Value / right.Value;
	public static bool operator *(AssemblerSymbol left, AssemblerSymbol right) => left.Value * right.Value;
}
```
#### Usage:
```
var c = new Assembler(64);
c.SymbolResolver += (e,s) => {
	if (s.Key == "Kernel32.ExitProcess")
		return 0x40000;
}
var symbol1 = c.CreateSymbol("Kernel32.ExitProcess");

c.sub(rsp,28)
c.mov(rax,1)
c.call(symbol1); // <-- which the assembler turns into c.call(0x40000) after resolving
c.add(rsp,28)
c.ret();
```

**Comment by xoofx** [comment]
Not really in favor of adding that. You can subclass Assembler class and provide this in your own project if you want.

Some folks could start to use enums for their symbols, others would use constants or unique non string key objects.  An implementation would have to be opinionated and that doesn't fit well in a general purpose. But the assembler class is now non sealed, so you can derive from it and implement whatever extended scenarios you want.

**Comment by 0xd4d** [comment]
You could also write your own `AssemblerSymbol` struct that will return the value. Either it knows the value or it will call some other class to get the value. The following example assumes it already knows the value.

```C#
readonly struct AssemblerSymbol {
    public readonly ulong Value;
    public AssemblerSymbol(ulong value) => Value = value;
    public static implicit operator ulong(AssemblerSymbol symbol) => symbol.Value;
}
```

Usage:

```C#
var my_symbol = GetMySymbol();
c.mov(rcx,my_symbol);
```

**Comment by Symbai** [comment]
Shouldn't it be possible to add overloads for methods accepting numbers to also take a string. Then calling the resolver and if it resolved, call the original method with the number from the resolver?

When adding this to the C# generator it wouldn't even be too much work. Or am I missing something?

**Comment by 0xd4d** [comment]
I don't think it's needed because anytime you do:

```C#
a.mov(rcx,"symbol");
```

you could instead do

```C#
a.mov(rcx,r("symbol"));
```

where `r` is your symbol resolver.

**Comment by Symbai** [comment]
That's a lot easier actually 😄 Guess that works for my purpose for now
