### ISSUE TITLE
Assembler - Support anonymous labels

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#71]
Some assembler support [anonymous labels](https://en.wikibooks.org/wiki/X86_Assembly/FASM_Syntax) which gives a better assembling flow when a label is required but naming is not.

Consider this small example:
```
var c = new Assembler(64);

var label1 = c.CreateLabel();

c.cmp(rax,5);
c.jge(label1);
c.add(rax, r15);
c.Label(ref label1);
c.ret();
```

With anonymous labels it would become shorter:
```
var c = new Assembler(64);

c.cmp(rax,5);
c.jge(@f); // jumps to the next label
c.add(rax, r15);
c.Label(@@);
c.ret();
```

In a larger context the benefit become more obvious, saving declaration of 6 labels:
```
var c = new Assembler(64);

c.cmp(rax,5);
c.jge(@f);  // jumps to the next label <---------
c.add(rax, r10);				|
						|
c.Label(@@); // <--------------------------------
c.cmp(rax,6);
c.jge(@f);  // jumps to the next label <---------
c.add(rax, r11);				|
						|
c.Label(@@); // <--------------------------------
c.cmp(rax,7);
c.jge(@f);  // jumps to the next label <---------
c.add(rax, r12);				|
						|
c.Label(@@);// <--------------------------------
c.cmp(rax,7);
c.jge(@f);  // jumps to the next label <---------
c.add(rax, r13);				|
						|
c.Label(@@);// <--------------------------------
c.cmp(rax,8);
c.jge(@f);  // jumps to the next label <---------
c.add(rax, r14);				|
						|
c.Label(@@);// <--------------------------------
c.cmp(rax,9);
c.jge(@f);  // jumps to the next label <---------
c.add(rax, r15);				|
c.Label(@@);// <--------------------------------
c.ret();
```
This could work too, depends on whether we allow it:
```
var c = new Assembler(64);
var label1 = c.CreateLabel():
c.cmp(rax,5);
c.jge(@f); // jumps to the next label, whether its anonymous or not (in this case its not)
c.add(rax, r15);
c.Label(label1);
c.ret();
```

Anonymous labels should not be available for getting their RIPs from, they're anonymous. And I am not sure about the syntax with using @ and how C# syntax deals with it. But in general the syntax should be as short as possible and as much different as possible to give contrast. And I find @ to be intuitive like in FASM.

**Comment by xoofx** [comment]
The closest viable API I can think ok would be around this:

```
c.LabelAnonymous(); // Emit an anonymous label
c.cmp(rax, 9);
c.jge(c.CurrentLabel);  // backward jump, already available in the API
c.jmp(c.NextAnonymousLabel); // forward jump to the following line (create implicitly an anonymous label and use it)
c.LabelAnonymous();
```

The `@` in C# can't do much miracle syntax wise, as it is only usable for escaping keyword, otherwise the following name has to be a standard variable/field name.

Another option would be to reserve Label.Id = 1 for backward and Label.Id = 2 for forward, and you would be able to use instead of `c.CurrentLabel` / `c.NextAnonymousLabel` a variable for these two, but it would have to be differentiated like for register names so that there is little chance to clash with existing user code (e.g `_lb_` for label backward, `_lf_` for label forward)

**Comment by Symbai** [comment]
Writing `LabelAnonymous/CurrentLabel/NextAnonymousLabel` is not exactly what I would prefer. First of all its not obvious that its anonymous, unless we might get syntax highlighting at some day,  and I prefer assembly being as much readable as possible. And its not short enough for me to feel convenient.

`_lb_` and `_lf_` comes closer to what I thought but I'm not fully satisfied either. We can leave this often for discussion and hearing other ideas / thoughts.
