### ISSUE TITLE
Add support for ARM?

### ISSUE THREAD

**Issue by xoofx** [0xd4d/iced#72]
Hey,
This is not something I need today, but I might be looking for in the future, but did you have in mind to make Iced also able to encode/decode ARM instruction set at some point?

The nice thing about ARM is that it seems that they have their entire instruction set available through a specification language (see for example [Dissecting ARM's Machine Readable Specification](https://alastairreid.github.io/dissecting-ARM-MRA/)) and that could help to automate the generation of encoders, decoders and assemblers.

**Comment by 0xd4d** [comment]
Yes, I've been thinking about supporting more archs and arm/aarch64 would be the most useful to support.

I don't know when I'll do it though.

**Comment by xoofx** [comment]
> I don't know when I'll do it though.

Same here, I don't need this for now, but good to know that it could be part of Iced!
I will be glad to help, no need to rush, I will come back on this when I will be actually looking for a support for it. I expect that the encoding/decoding for ARM should be more simple to develop than Intel.

**Comment by 0xd4d** [comment]
I'll create two new issues will close this.

**Comment by xoofx** [comment]
Just released https://github.com/xoofx/AsmArm64
