### ISSUE TITLE
Hide unnecessary assembler types by nesting into Assembler type

### ISSUE THREAD

**Issue by xoofx** [0xd4d/iced#74]
AssemblerRegister* and AssemblerMemoryOperand* with other associated types are available on the top level namespace `Iced.Intel` while they are of no usage for end user because they are made accessible via `AssemblerRegisters`.
I'm wondering if making all these types nested in `Assembler` would make the front-facing API a little bit more friendly, thoughts?
I can send a PR to correct this if you want.

**Comment by 0xd4d** [comment]
You want to remove them from completion lists? If so, I think there are attributes that can be added to them to prevent the user from seeing them. (`[EditorBrowsable(EditorBrowsableState.Never)]`) Or is there another reason you want them as nested types?

I think we should make most ctors and fields/properties internal. If we do, we can also make `AssemblerOperandFlags` and `MemoryOperandSize` internal. I don't think any user needs the fields/ctors or those two enums when using the `Assembler` API.

**Comment by xoofx** [comment]
Yeah, maybe, I can try.

**Comment by xoofx** [comment]
Fixed by #76
