### ISSUE TITLE
Relocs on RIP+offset addressing?

### ISSUE THREAD

**Issue by xoofx** [0xd4d/iced#78]
When using the assembler, I noticed that even if I pass `BlockEncoderOptions.ReturnRelocInfos` with an instruction like `lea, rsp, __[label]`, the label is not reported as a relocation. Is it expected or not?

Also, side question, I'm in the need also to specify a label bound to a specific absolute RIP, so basically an external symbol (would not be used through `Assembler.Label()`) and for which I would like the code to generate proper rel32 encoding for example. Is it going to work with the automatic fixup of the block encoder? (there is yet no API to allow to create a label with an absolute RIP, but I'm wondering even If I do that if this will work)

**Comment by 0xd4d** [comment]
The relocations are for stuff that the BlockEncoder creates, eg. if it rewrites `jmp too_far_away` to `jmp qword ptr [mem] ... mem: dq addr`. This can only happen in 64-bit mode.

> for which I would like the code to generate proper rel32 encoding for example. Is it going to work with the automatic fixup of the block encoder? 

If it's close enough (+/-2GB) it will work, but you must also update the instruction's `NextIP` property to some unique value close to the target and the displacement should equal `target - NextRIP` (must fit in an `int`).

**Comment by 0xd4d** [comment]
It's impossible for the encoder to know if some value is an offset or just an integer, eg. `mov rax,0x123456789ABCDEF0` is that the address of something or just a constant?

You can use the `ReturnConstantOffsets` option. They should have the offsets and sizes of each immediate / displacement so you could use that info to create some reloc infos.

**Comment by xoofx** [comment]
> You can use the ReturnConstantOffsets option. They should have the offsets and sizes of each immediate / displacement so you could use that info to create some reloc infos.

Right, ok I could do that.

> If it's close enough (+/-2GB) it will work, but you must also update the instruction's NextIP property to some unique value close to the target and the displacement should equal target - NextRIP (must fit in an int).

Ok, let's take an example: Suppose that have an external label with a specific RIP (e.g `c.CreateExternalLabel(rip)`) and then I would like to use it in `c.lea(rsp, __[myLabelWithRip]);`
How do you see this working? Should we do something like `c.NextRip(pseudoRIPCloseToMyLabelWithRip).lea(rsp, __[myLabelWithRip])` so that the lea could setup the NextRip?

**Comment by 0xd4d** [comment]
Maybe you could use negative ids to mean 'external label'. Before you call the BlockEncoder, you'd fix the IP of those instructions so the displacement is a valid int32 displacement.

One problem is that if you change the IP of the instruction, then any labels referencing it would need to be updated too, e.g this should still work:

```C#
c.lea(rax,__[lbl1]); //1
c.je(lbl1); //2
c.nop();
c.Label(ref lbl1);
c.lea(rcx,__[some_external_label]); //3
```

`//1` and `//2` reference the old label `lbl1` and must be updated to the new 'ip' of `//3` instead of `lbl1.id`

**Comment by xoofx** [comment]
I'm having trouble with the Assembler/BlockEncoder to actually even generate a correct `lea rsp, [rip + 0]`

With the assembler, I can't do that easily so I thought that I could do something like:

```
var label = new Label();
c.lea(rsp, __[label]);
``` 

but it generates something like:

```
000001BDCAD90000 67488D25F8FF2635                lea       rsp,[dword rel 0]
``` 

while I would expect to generate `48 8d 25 00 00 00 00    lea    rsp,[rip+0x0]`

but it looks like even If I pass `BlockEncoderOptions.DontFixBranches`, it is still modifying the label.

Also unlucky trying to create the instruction directly:

```
c.AddInstruction(Instruction.Create(Code.Lea_r64_m, rsp, new MemoryOperand(Register.RIP, Register.None, 1, 0, 1)));
```

Why is BlockEncoder still modifying the displacement and encoding that with a `67` prefix?

**Comment by xoofx** [comment]
Tried also with Encoder directly:

```
var mylea = Instruction.Create(Code.Lea_r64_m, rsp, new MemoryOperand(Register.RIP, Register.None, 1, 0, 1));
encoder.Encode(mylea, 0);
```

and it generates:

```
48 8D 25 F9 FF FF FF                  lea       rsp,[rel 0]
```

which is a displacement of -7, which goes back right to the beginning of the instruction... but now, I don't understand anymore `MemoryOperand.Displacement` which is an int, I thought it was a relative offset but it is not, or relative to the end of the instruction? It is quite confusing...

**Comment by 0xd4d** [comment]
The virtual address is calculated as: VA = rip_after_instruction (i.e., `instr.NextIP`) + displ

You're referencing RIP+0 which is NextRIP + 0 and since NextIP probably is 0, the VA = 0 + 0. Your instruction's IP is probably not within the first 2GB of the address space so it has to use an EIP relative addressing mode (not RIP relative).

The assembler is just a thin layer on top of the BlockEncoder which was added to support moving decoded instructions. If you create your own instructions you have to do a little more work if it's RIP relative addresses. Eg. if it's a decoded instruction, the NextIP + displ will always be correct and each instruction will have a unique IP so all branches reference only one instruction.

So you must initialize NextIP to some address close to the IP it will have when you encode it, and then set set: VA - rip_after_instruction (i.e., `instr.NextIP`) = displ

**Comment by 0xd4d** [comment]
It would be nice to improve the `BlockEncoder` but it's a future TODO. Any improvements to it will also improve the `Assembler`.

**Comment by xoofx** [comment]
> The virtual address is calculated as: VA = rip_after_instruction (i.e., instr.NextIP) + displ

Right, but then, with that code:

```c# 
var mylea = Instruction.Create(Code.Lea_r64_m, rsp, new MemoryOperand(Register.RIP, Register.None, 1, 0, 1));
mylea.NextIP = (ulong)mylea.Length; 
encoder.Encode(mylea, 0);
```

But Length is not known, but only return by Encode, so it is confusing that I would have to do a double pass to update the instruction?

Why for instance requiring to pass the RIP when encoding `Encoder.Encode`, while an instruction doesn't need any context of encoding. If you type `lea rsp, [rip + 0]` in an assembler, it is not going to require to specify a rip starting for the LEA and the next_rip after it...

It feels like instr.IP/instr.NextIP is certainly interesting for decoding, but I'm failing to see its practicability when encoding. It makes a simple encoding with a displacement very difficult to express.

**Comment by xoofx** [comment]
I think I'm gonna use a rip of 0 with the Assembler, encode a zero Label and patch the displacements after via the constant offsets.

**Comment by 0xd4d** [comment]
I've updated the displacement to a ulong so RIP-rel memory operands don't depend on the NextIP property. Maybe that will fix some/all of the problems you listed here.

**Comment by xoofx** [comment]
Cool, thanks! I will probably try that when I'll be back to my project that was using Iced!  😉
