### ISSUE TITLE
CI setup and NuGet packages

### ISSUE THREAD

**Issue by xoofx** [0xd4d/iced#8]
Hey,
I was wondering if you would be interested by a PR to setup a CI for this project (on AppVeyor or on Azure DevOPs) and a way to automatically publish a NuGet package easily (when you push a tag with a version number)
Let me know

**Comment by 0xd4d** [comment]
Yes, you can do that. I don't have a nuget account yet though.

I already use AppVeyor: https://ci.appveyor.com/project/0xd4d/iced

The only problem at the moment is that it doesn't run the unit tests because xunit must use the -noappdomain command line switch and their version doesn't seem to support it.

**Comment by xoofx** [comment]
> Yes, you can do that. I don't have a nuget account yet though.

Could you create a nuget account? After this, you can an api_key from nuget that you will be able to put in your `appveyor.yml` config (it's encrypted with your appveyor account so nobody can use it except you)

> I already use AppVeyor: https://ci.appveyor.com/project/0xd4d/iced

Great, you can export your setup to yml already and commit it as part of the repo (appveyor.yml)

> The only problem at the moment is that it doesn't run the unit tests because xunit must use the -noappdomain command line switch and their version doesn't seem to support it.

Hm, why do you require this? I can run dotnet tests on iced without any failure here

**Comment by 0xd4d** [comment]
I've added appveyor.yml

> Hm, why do you require this? I can run dotnet tests on iced without any failure here

I think dotnet tests uses .NET Core which doesn't have AppDomains. xunit on .NET Framework defaults to using AppDomains which makes running all tests very slow due to serialization and deserialization.

**Comment by xoofx** [comment]
I have been able to run the tests locally with a particular config. I have pushed a PR #11 to try this on appveyor, let's see.

**Comment by 0xd4d** [comment]
> It seems that you need to validate this appveyor build

How do I do that? Seems like it worked (Build Success), but it's still yellow for some reason.

**Comment by xoofx** [comment]
> How do I do that? Seems like it worked (Build Success), but it's still yellow for some reason.

You need probably to go to the appveyor (with you logged-in) and you should be able to launch the build manually at least. I have never done this on appveyor, but it should be possible directly there

**Comment by 0xd4d** [comment]
Your first build got green after 10 mins 6 s, it could be related to the many test cases, it wants to display everything under the tests tab, even if it passed. It stops after 30K test cases.

**Comment by xoofx** [comment]
han yes, maybe, never tried to run so many tests on appveyor actually 😅

**Comment by xoofx** [comment]
ok, it seems all green now

**Comment by 0xd4d** [comment]
Does `dotnet test -c` produce some xml file that is later read by appveyor? If that can be disabled, this long wait can probably be disabled, docs: https://www.appveyor.com/docs/running-tests/#calling-test-runners-from-your-custom-scripts

**Comment by xoofx** [comment]
> Yes, you can do that. I don't have a nuget account yet though.

can you create it? we would be able to make Iced available on NuGet 😉

**Comment by 0xd4d** [comment]
I just have to add one more breaking change and make the MemorySize prop read only too, should be fixed by tomorrow and then I'll add a 0.9 preview nuget package.

**Comment by 0xd4d** [comment]
Done.
