### ISSUE TITLE
How to get the offset of a register?

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#81]
The ConstantOffsets provide an option to get the offsets of for example Displacement. I would need something like that but for Opcode Registers + MemoryBase. Currently, I have to assemble an instruction first, change a register, assemble again and compare bytes to get the offset where they are different. This doesn't seem to be a good way. Is there an existing better way or a chance the registers can be added to ConstantOffsets?

**Comment by 0xd4d** [comment]
There's no such API because the register bits can be in many different locations, and sometimes you have to add a byte (REX prefix) if you want to use the higher regs.

**Comment by 0xd4d** [comment]
The only solution at the moment is to use an `OpCodeInfo` since it has info on where each operand is stored, eg. is the reg stored in modrm.reg etc. You have to implement your own prefix parser.
