### ISSUE TITLE
Add overload: Assembler.Assemble(out byte[] assembledBytes, ...)

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#82]
When quickly assembling I find it rather annoying to write these many lines all the time just to get the assembled bytes.

```
var stream = new MemoryStream();
c.Assemble(new StreamCodeWriter(stream), 0);
var assembledBytes = stream.ToArray();
//do stuff
```

Instead a new overload could become useful:
```
c.Assemble(out byte[] assembledBytes, 0);
//do stuff
```

At the moment I wrote an extension method myself but this will not avoid the additional allocation of calling ToArray() and I can imagine retrieving assembled bytes is used a lot so it might be worth officially supporting it.

**Comment by 0xd4d** [comment]
> At the moment I wrote an extension method myself but this will not avoid the additional allocation of calling ToArray()

You can write your own `CodeWriter` that re-uses the same array (or `List<byte>`). You can't remove allocating a `byte[]` since it's an `out` variable and owned by the caller.
