### ISSUE TITLE
How to change Assembler.Instructions?

### ISSUE THREAD

**Issue by ZQiu233** [0xd4d/iced#83]
It's a IReadOnlyList. I wonder how can I modify the value in it if I'm making an assembly-level optimizer.

Is there any way to easily remove an instruction in it which I might have ignored for there're so many methods in Assembler.

**Comment by xoofx** [comment]
There is no methods currently to remove an instruction on an `Assembler`. You can make a PR to add a `void RemoveInstructionAt(int index)` (note that `InsertInstructionAt` doesn't exist as well)

**Comment by ZQiu233** [comment]
> There is no methods currently to remove an instruction on an `Assembler`. You can make a PR to add a `void RemoveInstructionAt(int index)` (note that `InsertInstructionAt` doesn't exist as well)

Thanks a lot.
