### ISSUE TITLE
Jump Address

### ISSUE THREAD

**Issue by ruslan79k** [0xd4d/iced#89]
I'm new at this. I need to jump to the original program code, why does the jump address become different?

`c.jmp(0x0262A377);`  
jmp 05A2A377

**Comment by 0xd4d** [comment]
That instruction is an IP-relative instruction, so my guess is that you didn't initialize `decoder.IP` to the correct address of the instruction when decoding it (and later disassembling it). See the [README examples](https://github.com/0xd4d/iced/blob/master/src/csharp/Intel/README.md#disassemble-decode-and-format-instructions) on how to do this.

If that didn't fix it, add a minimal repro.
