### ISSUE TITLE
Can you support .Net 3.5?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/iced#92]
There're only 3 places should be modified:

`[MethodImpl(MethodImplOptions.AggressiveInlining)]`
`IReadOnlyCollection<T>`, `IReadOnlyList<T>`
`StringBuilder.Clear`

**Comment by 0xd4d** [comment]
1.4.0 was the last version that supported net35.

**Comment by CreateAndInject** [comment]
Do you know any similar project which support 3.5?
I remember you stared a similar repo, but I can't find it in your stars now.

**Comment by 0xd4d** [comment]
No, but you can search nuget
