### ISSUE TITLE
Add fuzz testing via mishegos

### ISSUE THREAD

**Issue by lzybkr** [0xd4d/iced#93]
I'd like to see how iced stacks up compared to xed w.r.t. correctness and mishegos looks like a good tool to compare disassemblers.  See https://github.com/trailofbits/mishegos/issues/3 - iced is on the list

Instructions for adding a new disassembler look relatively [simple](https://github.com/trailofbits/mishegos/blob/master/docs/adding_a_worker.md) - though iced might be a bit harder considering it's implemented in Rust.

**Comment by 0xd4d** [comment]
I'll have a look, but I can't promise a PR. Maybe the author will add it.

The output of iced has been compared against many other disassemblers, including XED, objdump (gas), ndisasm (nasm), dumpbin (masm). A couple of XED bugs were found and reported and they have since been fixed by the author.

**Comment by 0xd4d** [comment]
By author I mean the mishegos repo owner.

**Comment by 0xd4d** [comment]
I've sent a PR https://github.com/trailofbits/mishegos/pull/222

I'll close this when the PR gets merged/closed.
