### ISSUE TITLE
Cannot assemble "48 6B D0 88 - imul rdx,rax,88h"

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#96]
```
var c = new Assembler(64);
c.imul(rdx, rax, (byte)0x88);
```
always generates:
`48 69 D0 88 00 00 00 - imul rdx,rax,00000088`
but I want:
`48 6B D0 88 - imul rdx,rax,88h`
instead. How can I assemble this?

**Comment by 0xd4d** [comment]
> `48 6B D0 88 - imul rdx,rax,88h`

The immediate is sign extended. The disassembler you used is incorrect, it's `imul rdx,rax,0FFFFFFFFFFFFFF88h`

So you use that immediate or the int32/64 version of it: `-78h`
