### ISSUE TITLE
lea reg,[0x......] fails on GetUsedMemory()

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#97]
The following instruction has a memory displacement but calling GetUsedMemory() returns nothing.
`48 8D 05 B3 E4 01 00 - lea rax,[18001F4D0]`

```
0000000180001016 lea rax,[18001F4D0h]
    OpCode: REX.W 8D /r
    Instruction: LEA r64, m
    Encoding: Legacy
    Mnemonic: Lea
    Code: Lea_r64_m
    CpuidFeature: X64
    FlowControl: Next
    Displacement offset = 3, size = 4
    Op0Access: Write
    Op1Access: NoMemAccess
    Op0: r64_reg
    Op1: mem
    Used reg: RAX:Write
```
While when its a MOV instruction it works fine:
```
0000000180001016 mov rcx,[18001EA38h]
    OpCode: REX.W 8B /r
    Instruction: MOV r64, r/m64
    Encoding: Legacy
    Mnemonic: Mov
    Code: Mov_r64_rm64
    CpuidFeature: X64
    FlowControl: Next
    Displacement offset = 3, size = 4
    Memory size: 8
    Op0Access: Write
    Op1Access: Read
    Op0: r64_reg
    Op1: r64_or_mem
    Used reg: RCX:Write
    Used mem: [DS:0x18001EA38;UInt64;Read]
```
Is this a bug or by design (in such case: why?)?

**Comment by 0xd4d** [comment]
`LEA` doesn't access any memory.

**Comment by Symbai** [comment]
The second operator is memory `Op1: mem`. And I'm using GetUsedMemory to get the displacement address directly instead of doing the instruction address + displacement + instruction length calc myself. Can we perhaps get a property for displacement address then so I dont have to bloat up my code with several IF's and switches depending on the instruction mnemonic?

**Comment by 0xd4d** [comment]
> And I'm using GetUsedMemory to get the displacement address directly instead of doing the instruction address + displacement + instruction length calc myself

So you're only interested in IP relative memory addresses? There's a property to get the linear address: `IPRelativeMemoryAddress`

**Comment by 0xd4d** [comment]
> several IF's and switches depending on the instruction mnemonic?

Don't check the mnemonic, check the `OpCount` and call `GetOpKind()` to get the operand type.

**Comment by Symbai** [comment]
> 
> So you're only interested in IP relative memory addresses? There's a property to get the linear address: `IPRelativeMemoryAddress`

The `MemorySize` property is priceless as well but for LEA not important so I can use the `IPRelativeMemoryAddress` property here, thanks for the hint. 

But why shouldn't I check the mnemonic?! You mean because something like `lea reg,[reg+10]` ? I'm filtering these and others out already by `MemoryDisplacement < 0x10000` which seems to be an easier way.

**Comment by 0xd4d** [comment]
> But why shouldn't I check the mnemonic?!

You shouldn't use the mnemonic to check what kind of operands it uses, that's what `GetOpKind()` is for.
