### ISSUE TITLE
Assembler.db should have a byte[] overload

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#98]
Instead of being limited to 16 bytes only and/or having to manually type every byte, `Assembler.db()` should have a byte array overload. As these are already bytes the assembler doesn't have to assemble them but instead just copy them to the right IP.

**Comment by Nekketsu** [comment]
Shouldn't it be nice to have an overload of type:
```
public void db(params byte[] array)
```

So we can call it with an array of bytes, or an unlimited number of parmateres?
```
asm.db(0x1, 0x2, 0x3, ...); // Unlimited number of parameters, the compiler is in charge to convert it into an array
asm.db(new [] { 0x1, 0x2, 0x3 }); // It will work also with arrays
```
